import { contextBridge, ipcRenderer } from 'electron'

function on(channel, cb) {
  const h = (_e, payload) => cb(payload)
  ipcRenderer.on(channel, h)
  return () => ipcRenderer.removeListener(channel, h)
}

contextBridge.exposeInMainWorld('footage', {
  appVersion: () => ipcRenderer.invoke('app:version'),
  onUpdateStatus: (cb) => on('update:status', cb),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  openReleases: () => ipcRenderer.invoke('update:openReleases'),
  loadData: () => ipcRenderer.invoke('data:load'),
  saveData: (json) => ipcRenderer.invoke('data:save', json),
  saveDataSync: (json) => ipcRenderer.sendSync('data:saveSync', json),
  toolsStatus: (overrideDir) => ipcRenderer.invoke('tools:status', overrideDir),
  scan: (folders, files) => ipcRenderer.invoke('library:scan', folders, files),
  pickFiles: () => ipcRenderer.invoke('dialog:pickFiles'),
  onProbed: (cb) => on('library:probed', cb),
  getWaveform: (clip) => ipcRenderer.invoke('waveform:get', clip),
  requestWaveform: (clip, front) => ipcRenderer.invoke('waveform:request', clip, front),
  requestWaveforms: (clips) => ipcRenderer.invoke('waveform:requestMany', clips),
  clearWaveformQueue: () => ipcRenderer.invoke('waveform:clearQueue'),
  onWaveformEvent: (cb) => on('waveform:event', cb),
  audioFiles: (clip) => ipcRenderer.invoke('media:audioFiles', clip),
  setCachePolicy: (limitGB, mode) => ipcRenderer.invoke('cache:setPolicy', limitGB, mode),
  cacheStats: () => ipcRenderer.invoke('cache:stats'),
  trimCache: (keepClip) => ipcRenderer.invoke('cache:trim', keepClip),
  emptyCache: (keepClip) => ipcRenderer.invoke('cache:empty', keepClip),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  pickFolders: () => ipcRenderer.invoke('dialog:pickFolder'),
  listScripts: () => ipcRenderer.invoke('bijou:listScripts'),
  beatColors: () => ipcRenderer.invoke('bijou:beatColors'),
  exportToBijou: (opts) => ipcRenderer.invoke('bijou:export', opts),
  exportPremiere: (clips, kind, name) => ipcRenderer.invoke('export:premiere', clips, kind, name),
  showItem: (p) => ipcRenderer.invoke('shell:showItem', p),
  customThemes: () => ipcRenderer.invoke('bijou:customThemes'),
  isFrameless: () => ipcRenderer.invoke('window:frameless'),
  setOverlayColors: (colors) => ipcRenderer.invoke('window:overlayColors', colors),
  toggleFullscreen: () => ipcRenderer.invoke('window:toggleFullscreen'),
  recreateWindow: () => ipcRenderer.invoke('window:recreate'),
  transcriptState: () => ipcRenderer.invoke('transcript:state'),
  transcriptDoneMap: (clips) => ipcRenderer.invoke('transcript:doneMap', clips),
  readTranscript: (clip, track) => ipcRenderer.invoke('transcript:read', clip, track),
  requestTranscripts: (jobs, language, front) => ipcRenderer.invoke('transcript:request', jobs, language, front),
  cancelTranscripts: (key) => ipcRenderer.invoke('transcript:cancel', key),
  removeTranscript: (clip, track) => ipcRenderer.invoke('transcript:remove', clip, track),
  searchTranscripts: (query, clips) => ipcRenderer.invoke('transcript:search', query, clips),
  onTranscriptEvent: (cb) => on('transcript:event', cb),
  llmInstalled: () => ipcRenderer.invoke('llm:installed'),
  listProjects: (dir) => ipcRenderer.invoke('projects:list', dir),
  saveProject: (dir, p) => ipcRenderer.invoke('projects:save', dir, p),
  trashProject: (folder) => ipcRenderer.invoke('projects:trash', folder),
  listSections: (folder) => ipcRenderer.invoke('sections:list', folder),
  saveSection: (folder, s) => ipcRenderer.invoke('sections:save', folder, s),
  trashSection: (folder, id) => ipcRenderer.invoke('sections:trash', folder, id),
  pickProjectsDir: (current) => ipcRenderer.invoke('dialog:pickProjectsDir', current),
  defaultProjectsDir: () => ipcRenderer.invoke('app:defaultProjectsDir'),
  exportSection: (payload) => ipcRenderer.invoke('export:section', payload),
  summarize: (id, payload) => ipcRenderer.invoke('llm:summarize', id, payload),
  onLlmEvent: (cb) => on('llm:event', cb)
})
